name: Keep Supabase Active

on:
  schedule:
    # Run every 5 days at 3 AM UTC
    - cron: '0 3 */5 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X POST '${{ secrets.SUPABASE_URL }}/rest/v1/rpc/ping' \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"
        continue-on-error: true
      
      - name: Health Check
        run: echo "Pinged Supabase to prevent inactivity pause"
